from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path
from statistics import mean

ROOT = Path(__file__).resolve().parents[1]
EXP = ROOT / "experiments" / "support_v3_2026-06-02"
OUT_MD = EXP / "paper_table_previews_2026-06-11.md"
OUT_T1 = EXP / "table1_core5_preview.csv"
OUT_T2A = EXP / "table2a_sd3_preview.csv"

METHOD_LABELS = {
    "base_only": "RF reconstruction",
    "direct_target": "Direct target",
    "adaptive_full_generic_support": "Generic support",
    "support_v3_fixed": "Fixed DeCE-SD3",
    "support_v3_controller_rmsgap": "DeCE-RF-SD3",
    "flowedit": "FlowEdit-SD3",
    "flowalign": "FlowAlign-SD3",
    "splitflow": "SplitFlow-SD3",
}


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        rows = [r for r in csv.DictReader(handle)]
    return [r for r in rows if not any(v == k for k, v in r.items())]


def f(row: dict[str, str], key: str) -> float | None:
    value = row.get(key, "")
    if value in {"", "nan", "None", None}:
        return None
    try:
        return float(value)
    except ValueError:
        return None


def summarize_rows(rows: list[dict[str, str]], method_key: str = "method") -> list[dict[str, str]]:
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        method = row.get(method_key) or row.get("baseline") or ""
        if method:
            grouped[method].append(row)
    out = []
    for method, rs in grouped.items():
        def avg(key: str) -> str:
            vals = [v for r in rs if (v := f(r, key)) is not None]
            return f"{mean(vals):.4f}" if vals else ""
        success_vals = [r.get("task_success") for r in rs if r.get("task_success") not in {None, ""}]
        out.append({
            "method": method,
            "label": METHOD_LABELS.get(method, method),
            "n": str(len(rs)),
            "task_success_true": str(sum(v == "True" for v in success_vals)) if success_vals else "",
            "outside_l1": avg("outside_mask_l1"),
            "inside_l1": avg("inside_mask_l1"),
            "source_ssim": avg("source_ssim"),
            "source_ssim_luma": avg("source_ssim_luma"),
            "dino_source": avg("dino_source_similarity"),
            "edit_score": avg("edit_score"),
            "clip_delta": avg("clip_target_minus_source"),
            "runtime_s": avg("runtime_seconds"),
            "peak_mem_gb": avg("peak_gpu_memory_gb"),
        })
    return sorted(out, key=lambda r: r["label"])


def write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    fields = list(rows[0]) if rows else []
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def md_table(rows: list[dict[str, str]], fields: list[str]) -> str:
    lines = []
    lines.append("| " + " | ".join(fields) + " |")
    lines.append("| " + " | ".join(["---"] * len(fields)) + " |")
    for row in rows:
        lines.append("| " + " | ".join(row.get(field, "") for field in fields) + " |")
    return "\n".join(lines)


def main() -> None:
    e1 = summarize_rows(read_csv(EXP / "e1_core5_strict_metrics.csv"))
    write_csv(OUT_T1, e1)

    e2_rows = read_csv(EXP / "e2_reduced_rf_fixed_mask_metrics.csv")
    e2 = summarize_rows(e2_rows)
    e2 = [r for r in e2 if r["method"] in {"flowedit", "flowalign", "splitflow", "support_v3_controller_rmsgap"}]

    dg = summarize_rows(read_csv(EXP / "e1_t1_t4_directgeneric_metrics.csv"))
    dg = [r for r in dg if r["method"] in {"direct_target", "adaptive_full_generic_support"}]

    fixed_path = EXP / "e4_t1_t4_controller_base_metrics.csv"
    fixed = summarize_rows(read_csv(fixed_path)) if fixed_path.exists() else []
    fixed = [r for r in fixed if r["method"] == "support_v3_fixed"]

    table2a = dg + [r for r in e2 if r["method"] != "support_v3_controller_rmsgap"] + fixed + [r for r in e2 if r["method"] == "support_v3_controller_rmsgap"]
    write_csv(OUT_T2A, table2a)

    lines = [
        "# Paper Table Previews (2026-06-11)",
        "",
        "Generated by `scripts/build_paper_table_previews.py` from current CSV artifacts. These are legacy drafting previews, not camera-ready LaTeX tables.",
        "",
        "Current paper-facing tables are generated by `scripts/build_final_paper_tables.py` and written to `final_paper_tables_2026-06-11.md` plus the `*_final.csv` files.",
        "",
        "## Table 1 Preview: Strict Core-5 E1",
        "",
        "Source: `experiments/support_v3_2026-06-02/e1_core5_strict_metrics.csv`.",
        "",
        md_table(e1, ["label", "n", "task_success_true", "outside_l1", "inside_l1", "source_ssim", "dino_source", "edit_score", "clip_delta"]),
        "",
        "Success-note: `task_success_true` is a relation-style presence+relation count for T1/T2/T3 only. T4 recolor and T5 material replacement require operation-specific metrics and visual gates.",
        "",
        "## Table 2a Preview: Same-Backbone / SD3 Draft",
        "",
        "Sources: E2-A strict RF comparison, Phase-2 direct/generic gap-fill, and Fixed DeCE component cache. Native FLUX rows belong in Table 2b, not this table.",
        "",
        md_table(table2a, ["label", "n", "outside_l1", "inside_l1", "source_ssim", "source_ssim_luma", "dino_source", "edit_score", "clip_delta"]),
        "",
        "Caveat: rows are assembled from older aligned caches and mix E2-A strict rows with Phase-2 T1-T4 gap-fill rows. This preview is superseded by the audited T1-T5 common-subset final tables.",
        "",
        "## Immediate Paper Use",
        "",
        "- Use Table 1 preview for Core-5 headline drafting.",
        "- Use Table 2a preview only as a sanity preview; the final common-subset join is now frozen in `table2a_sd3_common_subset_final.csv`.",
        "- Keep RF-Solver-Edit, FireFlow, and ReFlex in Table 2b native-context rows with explicit FLUX backbone labels.",
    ]
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_T1}")
    print(f"wrote {OUT_T2A}")
    print(f"wrote {OUT_MD}")


if __name__ == "__main__":
    main()
